import cv2
import numpy as np
import sys
import imageio

def main():
    # Solve the full image generated by creating a final gif extracting the frames and combining them into a single image
    # First parameter is the combined image
    # Second parameter is the dimension: 2 (2 for 2x2 grid, 3 for 3x3 grid, etc.)

    # Read combined image
    combined_image = cv2.imread(sys.argv[1])

    # Split in N frames based on the dimension
    dimension = int(sys.argv[2])
    frame_height = combined_image.shape[0] // dimension
    frame_width = combined_image.shape[1] // dimension
    frames = []
    for i in range(dimension):
        for j in range(dimension):
            frame = combined_image[i * frame_height:(i + 1) * frame_height, j * frame_width:(j + 1) * frame_width]
            frames.append(frame)

    # Reverse the intermediate frames so the animation returns like a boomerang.
    frames.extend(frames[-2:0:-1])
    
    # Create a gif from the frames
    gif_path = "output/combined.gif"
    imageio.mimsave(gif_path, frames, duration=0.5, loop=0)

if __name__ == "__main__":
    main()

